# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.codex-radiation-therapy
canonical: http://hl7.org/fhir/us/codex-radiation-therapy
name: CodeX-Radiation-Therapy
status: active
version: 2.0.0
releaseLabel: trial-use  # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
fhirVersion: 4.0.1
copyrightYear: 2021+
title: "CodeX Radiation Therapy"
publisher:
  name: HL7 International / Cross-Group Projects
  url: http://www.hl7.org/Special/committees/cgp
  email: cgplist@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: CodeX™ Radiation Therapy is an initiative
  intended to assemble a core set of structured data elements for radiation therapy
  electronic health records.
license: CC0-1.0
dependencies:
  hl7.fhir.uv.extensions: 5.1.0-cibuild
  hl7.fhir.us.core: 
    version: 6.1.0
    id: hl7fhiruscore
  hl7.fhir.us.mcode: 
    version: current
    id: fhirmcode
  hl7.fhir.uv.ae-research-ig:
    version: 1.0.1
    id: vulcan

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

parameters:
  show-inherited-invariants: false
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
  version-comparison: last
  auto-oid-root: 2.16.840.1.113883.4.642.40.14
pages:
  index.md:
    title: Home
  overview.md:
    title: Overview
  history.md:
    title: Development History
  building_on_mcode.md:
    title: Building on mCODE
  building_the_ig.md:
    title: Building the Implementation Guide
  credits.md:
    title: Credits
  conformance.md:
    title: Conformance Expectations
  artifacts.html:
    title: Artifacts Summary
  dictionary.md:
    title: Data Dictionary
  change_log.md:
    title: Change Log
  downloads.md:
    title: Download Specification
  ImplementationGuide-hl7.fhir.us.codex-radiation-therapy.md:
    title: CodeX Radiation Therapy ImplementationGuide Resource
  representing_radiotherapy_treatment.md:
    title: Representing Radiotherapy Treatment 
menu:
  Home: index.html
  Table of Contents:  toc.html
  Background:
    Overview: overview.html
    History: history.html
    Building on mCODE: building_on_mcode.html
    Building the Implementation Guide: building_the_ig.html
    Credits: credits.html
  FHIR Artifacts:
    Profiles: artifacts.html#course-level-profiles
    Extensions: artifacts.html#extensions
    Value Sets: artifacts.html#terminology-value-sets
    Examples: artifacts.html#example-example-instances
    Capability Statements: artifacts.html#capability-statements
    Complete Listing: artifacts.html
  Conformance:
    Conformance:  conformance.html
  More:
    Representing Radiotherapy Treatment: representing_radiotherapy_treatment.html
    Radiotherapy Glossary:  http://hl7.org/fhir/us/mcode/glossary.html
    Data Dictionary: dictionary.html
    Change Log: change_log.html
    Download Specification: downloads.html
groups:
  CapabilityStatements:
    name: Capability Statements 
    description: Capability Statements 
    resources:
    - CodexRTServerCapabilityStatement
  CourseLevelProfiles:
    name: Course Level Profiles
    description: Course Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-course-prescription
    - StructureDefinition/codexrt-radiotherapy-planned-course
    - StructureDefinition/codexrt-radiotherapy-course-summary
  PhaseLevelProfiles:
    name: Phase Level Profiles
    description: Phase Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-phase-prescription
    - StructureDefinition/codexrt-radiotherapy-planned-phase
    - StructureDefinition/codexrt-radiotherapy-treated-phase
  PlanLevelProfiles:
    name: Plan Level Profiles
    description: Plan Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-plan-prescription
    - StructureDefinition/codexrt-radiotherapy-treatment-plan
    - StructureDefinition/codexrt-radiotherapy-treated-plan
  FractionLevelProfiles:
    name: Fraction Level Profiles
    description: Fraction Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-treated-fraction
    - StructureDefinition/codexrt-radiotherapy-treatment-session
  ProfilesForAllLevels:
    name: Profiles Referenced from All Levels
    description: Profiles referenced from all levels and throughout the radiotherapy workflow.
    resources:
    - StructureDefinition/codexrt-radiotherapy-volume
    - StructureDefinition/codexrt-radiotherapy-treatment-device
    - StructureDefinition/codexrt-radiotherapy-seed-device
    - RadiotherapyAdverseEvent
    - RadiotherapyDiseaseStatus
  Extensions:
    name: Extensions
    description: Extensions used by radiotherapy profiles.  See []() for a description of where these are included.
    resources:
    - RadiotherapyFractionsPrescribed
    - RadiotherapyFractionsPlanned
    - RadiotherapyFractionsDelivered
    - RadiotherapyFractionNumberInPlan
    - RadiotherapyFractionNumberInPhase
    - RadiotherapySessionNumber
    - RadiotherapyDosePrescribedToVolume
    - RadiotherapyDosePlannedToVolume
    - RadiotherapyEnergyOrIsotope
    - DicomReference
    - RadiotherapyTreatmentApplicatorType
    - UniformFractionation
    - PrimaryPlanDose
    - PointDose
    - RadiotherapyReasonForRevisionOrAdaptation
    - RadiotherapyRespiratoryMotionManagement
    - RadiotherapyFreeBreathingMotionManagementTechnique
    - CourseInvolvesReirradiation
    - ImageGuidedRadiotherapyModality
    - RadiotherapyVolumeExtension
    - RadiotherapyDiseaseProgressionQualifier
    - RadiobiologicMetric
    - IntrafractionVerification
  #  - AdverseEventSeverityOrGrade

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: cgp