# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.codex-radiation-therapy
canonical: http://hl7.org/fhir/us/codex-radiation-therapy
name: CodeX-Radiation-Therapy
status: draft
version: 1.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
title: "CodeX™ Radiation Therapy"
publisher:
  name: HL7 Cross Group Projects Work Group
  url: https://www.hl7.org/Special/committees/cgp
  email: cgplist@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: CodeX™ Radiation Therapy is an initiative
  intended to assemble a core set of structured data elements for radiation therapy
  electronic health records.
license: CC0-1.0
dependencies:
  hl7.fhir.us.core: 4.0.0
  hl7.fhir.us.mcode: 2.0.0
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
pages:
  index.md:
    title: Home
  conformance-general.md:
    title: Conformance Expectations
  conformance-profiles.md:
    title: Profile Conformance
  terminology.md:
    title: Terminology
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  valuesets.md:
    title: Value Sets
  codesystems.md:
    title: Code Systems
  capabilitystatements.md:
    title: Capability Statements
  artifacts.html:
    title: Artifacts Summary
  basic_examples.md:
    title: Basic Examples
  examples.md:
    title: Extended Example
  dictionary.md:
    title: Data Dictionary
  change_log.md:
    title: Change Log
  downloads.md:
    title: Download Specification
  glossary.md:
    title: Radioterapy Glossary

menu:
  Home: index.html
  Conformance:
    General Expectations: conformance-general.html
    Profile Conformance: conformance-profiles.html
    Terminology: terminology.html
  FHIR Artifacts:
    Profiles: artifacts.html#a-course-level-profiles
    Extensions: artifacts.html#structures-extension-definitions
    Value Sets: artifacts.html#terminology-value-sets
    Code Systems: artifacts.html#terminology-code-systems
    Examples: artifacts.html#example-example-instances
    Capability Statements: capabilitystatements.html
    Complete Listing: artifacts.html
  More:
    Basic Examples: basic_examples.html
    Extended Example: examples.html
    Data Dictionary: dictionary.html
    Radiotherapy Glossary:  glossary.html
    Change Log: change_log.html
    Download Specification: downloads.html
    Other Versions: http://hl7.org/fhir/us/codex-radiation-therapy/history.html
groups:
  CourseLevelProfiles:
    name: A. Course Level Profiles
    description: Course Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-course-prescription
    - StructureDefinition/codexrt-radiotherapy-planned-course
    - StructureDefinition/codexrt-radiotherapy-course-summary
  PhaseLevelProfiles:
    name: B. Phase Level Profiles
    description: Phase Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-phase-prescription
    - StructureDefinition/codexrt-radiotherapy-planned-phase
    - StructureDefinition/codexrt-radiotherapy-treated-phase
  PlanLevelProfiles:
    name: C. Plan Level Profiles
    description: Plan Level Profiles
    resources:
    - StructureDefinition/codexrt-radiotherapy-plan-prescription
    - StructureDefinition/codexrt-radiotherapy-treatment-plan
    - StructureDefinition/codexrt-radiotherapy-treated-plan
  ProfilesForAllLevels:
    name: D. Profiles Referenced from All Levels
    description: Profiles referenced from all levels and throughout the Radiotherapy workflow.
    resources:
    - StructureDefinition/codexrt-radiotherapy-volume

  # Leaving the following groups autogenerated. If specific grouping is needed,
  # then uncomment here and make sure all Extensions, CodeSystems, ValueSets are listed here.
  # Extensions:
  #   name: Extensions
  #   description: Extensions.
  #   resources:
  #   - StructureDefinition/codexrt-radiotherapy-energy-or-isotope
  #   - StructureDefinition/codexrt-radiotherapy-fractions-delivered
  #   - StructureDefinition/codexrt-radiotherapy-fractions-planned
  #   - StructureDefinition/codexrt-radiotherapy-fractions-prescribed
  #   - StructureDefinition/codexrt-radiotherapy-dose-planned-to-volume
  #   - StructureDefinition/codexrt-radiotherapy-dose-prescribed-to-volume
  #   - StructureDefinition/codexrt-radiotheraphy-treatment-device-manufacturer
  #   - StructureDefinition/codexrt-radiotheraphy-treatment-applicator-type
  #   - StructureDefinition/codexrt-dicom-reference

  # CodeSystems:
  #   name: CodeSystems
  #   description: Code Systems.
  #   resources:
  #   - CodeSystem/radiotherapy-request
  #   - CodeSystem/snomed-requested-cs

  # ValueSets:
  #   name: ValueSets
  #   description: ValueSets.
  #   resources:
  #   - ValueSet/codex-radiotherapy-isotopes
  #   - ValueSet/radiotherapy-energy-units
  #   - ValueSet/radiotherapy-request
