# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.codexrt
canonical: http://hl7.org/fhir/us/codex-radiation-therapy
name: CodeX-Radiation-Therapy
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
title: "CodeX™ Radiation Therapy"
publisher:
  name: HL7 International Clinical Interoperability Council
  url: http://www.hl7.org/Special/committees/cic
  email: ciclist@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: CodeX™ Radiation Therapy is an initiative
  intended to assemble a core set of structured data elements for radiation therapy
  electronic health records.
license: CC0-1.0
dependencies:
  hl7.fhir.us.core: 4.0.0
  hl7.fhir.us.mcode: current
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
